# BY THEBJOREDCRAFT
# Altert Permission: fightalert.getalert

AlertMessage: "<color:#3b92d1>Der Spieler <color:#40d1db>%damager% <color:#3b92d1>hat <color:#40d1db>%target% <color:#3b92d1>angegriffen!"